# Copyright (c) 2022 RodKingroo
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 160)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.temp = QtWidgets.QLabel(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(10, 10, 380, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.temp.setFont(font)
        self.temp.setObjectName("temp")
        self.hum = QtWidgets.QLabel(self.centralwidget)
        self.hum.setGeometry(QtCore.QRect(10, 30, 380, 20))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.hum.setFont(font)
        self.hum.setObjectName("hum")
        self.min_t = QtWidgets.QLabel(self.centralwidget)
        self.min_t.setGeometry(QtCore.QRect(10, 50, 380, 20))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.min_t.setFont(font)
        self.min_t.setObjectName("min_t")
        self.max_t = QtWidgets.QLabel(self.centralwidget)
        self.max_t.setGeometry(QtCore.QRect(10, 90, 380, 20))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.max_t.setFont(font)
        self.max_t.setObjectName("max_t")
        self.pres = QtWidgets.QLabel(self.centralwidget)
        self.pres.setGeometry(QtCore.QRect(10, 110, 380, 20))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.pres.setFont(font)
        self.pres.setObjectName("pres")
        self.feels = QtWidgets.QLabel(self.centralwidget)
        self.feels.setGeometry(QtCore.QRect(10, 130, 380, 20))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.feels.setFont(font)
        self.feels.setObjectName("feels")
        self.ave_t = QtWidgets.QLabel(self.centralwidget)
        self.ave_t.setGeometry(QtCore.QRect(10, 70, 380, 20))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.ave_t.setFont(font)
        self.ave_t.setObjectName("ave_t")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather Omsk: Now"))
        self.temp.setText(_translate("MainWindow", "Text"))
        self.hum.setText(_translate("MainWindow", "Text"))
        self.min_t.setText(_translate("MainWindow", "Text"))
        self.max_t.setText(_translate("MainWindow", "Text"))
        self.pres.setText(_translate("MainWindow", "Text"))
        self.feels.setText(_translate("MainWindow", "Text"))
        self.ave_t.setText(_translate("MainWindow", "Text"))
